name: CI

on: [push, pull_request]

jobs:
  ##### Rust check, test, fmt, clippy
  check:
    name: Rust cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check
  test:
    name: Rust cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
  fmt:
    name: Rust cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt --all --check
  clippy:
    name: Rust cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo clippy -- -D warnings